name: Greasy Fork Sync

on:
  push:
    branches:
      - master
    paths:
      - 'mrlookup.js'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get repository info
        id: repo
        run: |
          echo "::set-output name=owner::$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)"
          echo "::set-output name=repo::$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)"
          
      - name: Create webhook payload
        run: |
          echo '{
            "ref": "refs/heads/master",
            "repository": {
              "full_name": "${{ steps.repo.outputs.owner }}/${{ steps.repo.outputs.repo }}",
              "html_url": "https://github.com/${{ steps.repo.outputs.owner }}/${{ steps.repo.outputs.repo }}"
            },
            "commits": [{
              "id": "${{ github.sha }}",
              "modified": ["mrlookup.js"]
            }]
          }' > webhook_payload.json
          
      - name: Send webhook to Greasy Fork
        env:
          WEBHOOK_SECRET: ${{ secrets.GREASYFORK_WEBHOOK_SECRET }}
        run: |
          # Calculate the signature
          SIGNATURE=$(openssl dgst -sha256 -hmac "$WEBHOOK_SECRET" webhook_payload.json | cut -d' ' -f2)
          
          # Send the webhook with the signature
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: sha256=$SIGNATURE" \
            -H "X-GitHub-Event: push" \
            -d @webhook_payload.json \
            https://greasyfork.org/zh-CN/users/159104-abel-van/webhook 