name: Notify Greasy Fork Update

on:
  push:
    branches:
      - master
    paths:
      - 'mrlookup.js'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const commit = context.sha;
            const commitUrl = `https://github.com/${owner}/${repo}/commit/${commit}`;
            
            await github.rest.issues.create({
              owner,
              repo,
              title: '⚠️ Greasy Fork Update Required',
              body: `A new version has been pushed to the repository. Please update the script on Greasy Fork.\n\n` +
                    `- Commit: ${commitUrl}\n` +
                    `- Greasy Fork URL: https://greasyfork.org/scripts/35116-mrlookup/edit\n\n` +
                    `Please copy the latest version from the repository and update it on Greasy Fork.`
            }); 